regions:
  djelfa: 'الجلفة'
  alger: 'الجزائر'
  adrar: 'أدرار'

pdf_links:
  djelfa: 'https://www.marw.dz/media/calendrier/1442/djelfa.pdf'
  alger : 'https://www.marw.dz/media/calendrier/1442/alger.pdf'
  adrar : 'https://www.marw.dz/media/calendrier/1442/adrar.pdf'


pdf_paths:
  djelfa: 'assets/20-21/pdfs/djelfa.pdf'
  alger : 'assets/20-21/pdfs/alger.pdf'
  adrar : 'assets/20-21/pdfs/adrar.pdf'

tabula_templates:
  djelfa: 'assets/20-21/tabula-templates/djelfa.json'
  alger: 'assets/20-21/tabula-templates/alger.json'
  adrar: 'assets/20-21/tabula-templates/adrar.json'

wilayas_file: 'assets/wilayas.json'

mawaqit_for_wilayas_dir: 'assets/20-21/mawaqit'

column_names:
  diff: 'الفروق'
  date: 'الموافق'
  qibla: 'القبلة'
  zawal: 'الزوال'
  dhohr: 'الظهر'
  wilaya: 'الولاية'
  salat_name: 'صلاة'
  salat_time: 'الوقت'

column_names_en:
  diff: 'diff'
  date: 'date'
  qibla: 'qibla'
  zawal: 'zawal'
  dhohr: 'dhohr'
  wilaya: 'wilaya'
  salat_name: 'salat_name'
  salat_time: 'salat_time'
  
salawat:
  fajr: 'الفجر'
  chorok: 'الشروق'
  dhohr: 'الظهر'
  asr: 'العصر'
  maghrib: 'المغرب'
  icha: 'العشاء'

salawat_en:
  fajr: 'fajr'
  chorok: 'chorok'
  dhohr: 'dhohr'
  asr: 'asr'
  maghrib: 'maghrib'
  icha: 'icha'

salawat_names:
  - 'الفجر'
  - 'الشروق'
  - 'الظهر'
  - 'العصر'
  - 'المغرب'
  - 'العشاء'

salawat_names_en:
  - 'fajr'
  - 'chorok'
  - 'dhohr'
  - 'asr'
  - 'maghrib'
  - 'icha'

api:
  title: 'Mawaqit salat API'
  description: 'Provides correct Mawaqit extracted from ministry website https://marw.dz'

user_agent: 'SalatDz/0.1'
